# Site settings
title: frncscgmz
email: mail@frncscgmz.me
description: > # this means to ignore newlines until "baseurl:"
  Programer/Engineer/Lover, most of the time.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://frncscgmz.me" # the base hostname & protocol for your site
twitter_username: frncscgmz
github_username:  frncscgmz

# Build settings
markdown: kramdown

# Octopress migration
permalink: /blog/:year/:month/:day/:title/
